# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9998:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "9997:3000"
    env_file:
      - BlogApi/.env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
